[package]
name = "birb-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = "2.0.104"
birb-common = { path="../birb-common" }
proc-macro2 = "1.0.95"
